@startuml c2
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container_Ext(web, "Веб-клиент")
Container_Ext(extDevices, "Датчики")

Container(clientsApi, "clientsApi")
Container(devices, "devices")

ContainerQueue(changes, "changes")
ContainerQueue(newData, "newData")

Container(devicesApi, "devicesApi")
Container(poller, "poller")
Container(changer, "changer")

Rel(web, clientsApi, "asd", "dsf")
Rel(clientsApi, devices, "asd", "dsf")


Rel(poller, newData, "asd")
Rel(newData, devices, "asd")


Rel(poller, devicesApi, "asd", "dsf")

Rel(devices, changes, "asd", "dsf")

Rel(changes, changer, "asd", "dsf")
Rel(changer, devicesApi, "asd", "dsf")

Rel(devicesApi, extDevices, "asd", "dsf")



@enduml