version: '3.8'

services:
  telemetry-service:
    build: ./telemetry-service
    container_name: telemetry-service
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: https://influxdb:8086
      DATABASE_TOKEN: F-QFQpmCL9UkR3qyoXnLkzWj03s6m4eCvYgDl1ePfHBf9ph7yxaSgQ6WN0i9giNgRTfONwVMK1f977r_g71oNQ==
      DATABASE_ORG: smarthome
      DATABASE_BUCKET: telemetry
      SERVER_PORT: 8081
    depends_on:
      - influxdb
    networks:
      - internal

  influxdb:
    image: influxdb:2.0.7
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: smarthome
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: F-QFQpmCL9UkR3qyoXnLkzWj03s6m4eCvYgDl1ePfHBf9ph7yxaSgQ6WN0i9giNgRTfONwVMK1f977r_g71oNQ==
    ports:
      - "8086:8086"
    networks:
      - internal

  devices-service:
    build: ./devices-service
    container_name: devices-service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=devices
      - DATABASE_HOST=db
      - SERVER_PORT=8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devices
    volumes:
      - ./devices-service/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d devices'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
networks:
  internal: