@startuml er-users-houses
title Users-Houses ER-diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

entity User {
  * user_id : UUID <<PK>>
  --
  name : varchar
  email : varchar
  phone_number : varchar
  birth : timestamp
  created_at : timestamp
  updated_at : timestamp
}

entity House {
  * house_id : UUID <<PK>>
  --
  address : varchar
  rooms_num : integer
  owner_id : UUID <<FK>>
}

entity Device {
  * device_id : UUID <<PK>>
  --
  device_type : varchar
  status : varchar
  house_id : varchar
  created_by : UUID <<FK>>
}

User ||--o{ House : "has"
User ||--o{ Device : "has"
House ||--o{ Device : "has"

@enduml