version: '3.8'

services:
  telemetry-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=c1UoVT1vzoXqucGstqIdXTBX-SNAaS-y8ce3QFQL7Y_1fNYJ_jcg9BUEvCLY2YzrbjY7Pax652WZEo2_4BQeTw==
      - INFLUXDB_ORG=your-org
      - INFLUXDB_BUCKET=your-bucket
    networks:
      - app_network
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: your-bucket
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - app_network
volumes:
  influxdb-data:
networks:
  app_network:
    driver: bridge